version: '3'
services:
  nginx:
    build: .
    ports:
      - "443:443"
    environment:
      - ALLOWED_CLIENT_S_DN='/C=IL/ST=Israel/O=Company'
    volumes:
      - type: bind
        source: certs
        target: /etc/nginx/conf.d/certs
